name: catkin_build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic
    steps:
      - name: Install basic ROS requirements
        run: |
          apt-get update && \
          apt-get install -y python3-pip ros-noetic-catkin python3-catkin-tools
      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/ros-global-localization

      - name: Install ros-global-localization requirements
        run: ./catkin_ws/src/ros-global-localization/install_requirements.sh
      - run: apt-get install -y ros-noetic-tf2-eigen
      - run: apt-get install -y ros-noetic-pcl-conversions ros-noetic-pcl-ros

      - name: catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build
